# Generated by Django 4.2.4 on 2023-08-08 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_nutshell'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutshell',
            name='detail',
            field=models.CharField(max_length=160),
        ),
    ]
