# Generated by Django 4.2.4 on 2023-08-11 05:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutshell',
            name='detail',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
